import os

replacements = [
    ("Are you sure you want to restart the program? All connections will be disconnected after restart, please proceed with caution!", "确定要重启程序吗？重启后所有连接都会断开，请谨慎操作！"),
    ('Are you sure you want to delete mount point "', '确定要删除挂载点 "'),
    ('Are you sure you want to delete user "', '确定要删除用户 "'),
    ("Are you sure you want to logout?", "确定要退出登录吗？"),
    ('"? This action cannot be undone.', '" 吗？此操作无法撤销。'),
    ("Real-time monitoring of NTRIP data streams and base station status", "NTRIP 数据流与基准站状态实时监控"),
    ("can only contain English letters, numbers, underscores and hyphens, no other special symbols, Chinese characters or other characters are allowed", "只能包含英文字母、数字、下划线和连字符，不允许其他特殊符号、中文或其他字符"),
    ("Administrator username cannot be modified", "管理员用户名不可修改"),
    ("Base Station STR Information", "基准站 STR 信息"),
    ("Base Station Information", "基准站信息"),
    ("Base Station Location", "基准站位置"),
    ("Change Admin Password", "修改管理员密码"),
    ("Confirm Delete Mount Point", "确认删除挂载点"),
    ("Confirm Delete User", "确认删除用户"),
    ("Confirm Logout", "确认退出登录"),
    ("Confirm Restart", "确认重启"),
    ("Connection Failed", "连接失败"),
    ("Connection Statistics", "连接统计"),
    ("Data Transfer:", "数据传输："),
    ("Edit Mount Point - ", "编辑挂载点 - "),
    ("Edit User - ", "编辑用户 - "),
    ("Enter mount point name", "请输入挂载点名称"),
    ("Enter new password", "请输入新密码"),
    ("Enter password again", "请再次输入密码"),
    ("Enter username, leave blank for no binding", "请输入用户名，留空表示不绑定"),
    ("Failed to add mount point: ", "添加挂载点失败："),
    ("Failed to add user: ", "添加用户失败："),
    ("Failed to call RTCM parsing API", "调用 RTCM 解析接口失败"),
    ("Failed to change password: ", "修改密码失败："),
    ("Failed to delete mount point: ", "删除挂载点失败："),
    ("Failed to delete user: ", "删除用户失败："),
    ("Failed to load application information:", "加载应用信息失败："),
    ("Failed to load page content, please try again later.", "页面内容加载失败，请稍后再试。"),
    ("Failed to restart program: ", "重启程序失败："),
    ("Failed to start RTCM parsing: ", "启动 RTCM 解析失败："),
    ("Failed to update mount point: ", "更新挂载点失败："),
    ("Failed to update user: ", "更新用户失败："),
    ("Leave blank to keep current password", "留空表示保持当前密码"),
    ("Loading STR table data...", "正在加载 STR 表数据..."),
    ("Mount Point Details", "挂载点详情"),
    ("Mount Point Management", "挂载点管理"),
    ("Mount Point Name", "挂载点名称"),
    ("Mount Point:", "挂载点："),
    ("Mount point name length must be between 3-50 characters", "挂载点名称长度必须在 3-50 个字符之间"),
    ("Network Bandwidth", "网络带宽"),
    ("New Password (NTRIP 1.0)", "新密码（NTRIP 1.0）"),
    ("New Password (Optional)", "新密码（可选）"),
    ("No STR table data available", "暂无 STR 表数据"),
    ("No changes made", "未做任何修改"),
    ("No data available", "暂无数据"),
    ("No mount point data available", "暂无挂载点数据"),
    ("No user binding", "不绑定用户"),
    ("Password (NTRIP 1.0)", "密码（NTRIP 1.0）"),
    ("Password length must be between 6-100 characters", "密码长度必须在 6-100 个字符之间"),
    ("Password must be at least 6 characters long", "密码长度至少为 6 个字符"),
    ("Please click the INFO button in the STR table to select a mount point", "请点击 STR 表中的 INFO 按钮选择挂载点"),
    ("Please enter new password and confirm password", "请输入新密码并确认密码"),
    ("Program restart command sent, system will restart in 3 seconds...", "重启命令已发送，系统将在 3 秒后重启..."),
    ("Refreshing STR table data...", "正在刷新 STR 表数据..."),
    ("Restart Program", "重启程序"),
    ("Restart failed: ", "重启失败："),
    ("Satellite Data Visualization", "卫星数据可视化"),
    ("Security Settings", "安全设置"),
    ("Signal Strength: ", "信号强度："),
    ("Station ID:", "基准站 ID："),
    ("STR Data Table", "STR 数据表"),
    ("System Control", "系统控制"),
    ("System Settings", "系统设置"),
    ("System Status", "系统状态"),
    ("The two passwords entered do not match", "两次输入的密码不一致"),
    ("Unknown Status", "未知状态"),
    ("Unknown error", "未知错误"),
    ("User Management", "用户管理"),
    ("Username length must be between 3-50 characters", "用户名长度必须在 3-50 个字符之间"),
    ("Waiting for data", "等待数据"),
    ("Waiting for location data...", "等待位置数据..."),
    ("Waiting for satellite data...", "等待卫星数据..."),
    ("Waiting for selection", "等待选择"),
    ("Active Connections:", "活跃连接："),
    ("Add Mount Point", "添加挂载点"),
    ("Add User", "添加用户"),
    ("Administrator password changed successfully", "管理员密码修改成功"),
    ("Antenna Serial:", "天线序列号："),
    ("Antenna Type:", "天线类型："),
    ("Band: ", "频段："),
    ("Bind User (NTRIP 2.0)", "绑定用户（NTRIP 2.0）"),
    ("CPU Usage", "CPU 使用率"),
    ("Cancel", "取消"),
    ("Channel: ", "通道："),
    ("City:", "城市："),
    ("Connected", "已连接"),
    ("Connecting...", "连接中..."),
    ("Connect Time", "连接时间"),
    ("Coordinates:", "坐标："),
    ("Country:", "国家/地区："),
    ("Data Packets", "数据包"),
    ("Delete", "删除"),
    ("Description", "描述"),
    ("Disconnected", "已断开"),
    ("Edit", "编辑"),
    ("Elevation: ", "高度角："),
    ("Error: ", "错误："),
    ("Frequency: ", "频率："),
    ("Height: ", "高度："),
    ("INFO", "详情"),
    ("Last Updated: ", "最后更新："),
    ("Latitude: ", "纬度："),
    ("Loading...", "加载中..."),
    ("Longitude: ", "经度："),
    ("Max Connections:", "最大连接："),
    ("Memory Usage", "内存使用"),
    ("Mount Point", "挂载点"),
    ("New Password:", "新密码："),
    ("New password", "新密码"),
    ("Confirm password", "确认密码"),
    ("Confirm Password:", "确认密码："),
    ("Offline", "离线"),
    ("Online", "在线"),
    ("Online Mount Points:", "在线挂载点："),
    ("Owner", "所有者"),
    ("Password", "密码"),
    ("Receiving", "接收中"),
    ("Reconnecting...", "重连中..."),
    ("Rejected Connections:", "拒绝连接："),
    ("Save", "保存"),
    ("Selected", "已选择"),
    ("Status", "状态"),
    ("Total Connections:", "总连接数："),
    ("Unknown", "未知"),
    ("Uptime", "运行时间"),
    ("User Connections:", "用户连接："),
    ("Users", "用户"),
    ("Username", "用户名"),
    ("Actions", "操作"),
    ("cannot be empty", "不能为空"),
    ("ECEF:", "地心地固坐标："),
    ("Mount Name Label", "挂载点名称标签"),
    ("YES", "确认"),
    ("OK", "确定"),
    ("Add", "添加"),
    (" X: ", " X："),
    (", Y: ", "，Y："),
    (", Z: ", "，Z："),
    (" Y: ", " Y："),
    (" Z: ", " Z："),
    ("Azimuth: ", "方位角："),
    ("Unspecified", "未指定"),
    ("Enter username", "请输入用户名"),
    ("Enter password", "请输入密码"),
    ("Connections", "连接数"),
    ("Mount point name", "挂载点名称"),
    ("' + 'Online Mount Points:', "' + '在线挂载点："),
    ("Online 挂载点s:", "在线挂载点："),
    ("Unauthorized access", "未授权访问"),
    ("HTTP ", "HTTP 错误 "),
]

with open('static/app.js', 'r', encoding='utf-8') as f:
    content = f.read()

for old, new in replacements:
    content = content.replace(old, new)

with open('static/app.js', 'w', encoding='utf-8') as f:
    f.write(content)

os.remove('translate_app.js.py')
print('done')
